### ISSUE TITLE
Design issue (MyAccount)

### ISSUE THREAD

**Issue by fahad-cb** [arslancb/clipbucketv2#10]
Whenever CLick on photos section and collection section 
left menu design got ruined !

http://107.181.179.12/f-clipbucket27/manage_collections.php?mode=add_new

http://107.181.179.12/f-clipbucket27/manage_photos.php

**Comment by sakydev** [comment]
@fahad-cb The same main.less problem. Reverting that to non compiled file should fix because I just tried it on local.

**Comment by fahad-cb** [comment]
fixed
