### ISSUE TITLE
Manage Groups: In manage groups the groups that the admin owns are not shown.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#109]
Steps:
1- Go to manage Groups page.
2- See the groups.

Result:
Not all groups made by admin are shown.
![admin_is_the_owner_and_groups_are_not_shown_in_managed_groups](https://cloud.githubusercontent.com/assets/12610575/7936027/2018944e-094f-11e5-9135-db250e898796.png)

**Comment by shoaib-dev** [comment]
Fixed.
