### ISSUE TITLE
Manage Contacts: No message on having no videos.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#121]
Steps:
1- Go to manage contacts.
2- Go to any user's page by clicking on the link. 

Actual Result:
If there is no video then no message is shown.
![no_message_on_having_no_videos](https://cloud.githubusercontent.com/assets/12610575/7936784/24b64e46-0955-11e5-94ba-12cc570acca6.png)

**Comment by sakydev** [comment]
Killed.
