### ISSUE TITLE
Video time shown on home page and watch video page is different.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#130]
![check_out_the_time](https://cloud.githubusercontent.com/assets/12610575/7979779/a6d9c15c-0abb-11e5-96a2-6b831a668886.png)
![check_the_time_now](https://cloud.githubusercontent.com/assets/12610575/7979781/a6dce90e-0abb-11e5-8a56-a01961c4d521.png)

**Comment by fahad-cb** [comment]
fixed
