### ISSUE TITLE
Weird collapse-handling for subcategories

### ISSUE THREAD

**Issue by mj1985** [arslancb/clipbucketv2#136]
When having two categories with subcategories, it isn't possible to collapse the second one alone.
Everytime you click on one of the parent category, both subcategories open
Exp:
http://videos.drhouse-forum.de/videos/

BTW: Why don't you use bootstrap vor this?!

**Comment by mj1985** [comment]
Solution (with bootstrap):
File to edit (includes/classes/category.class.php):
around line 322:

```
            $html .= "<span id='".$cat['category_id']."_toggler' alt='".$cat['category_id']."_categories' class='CategoryToggler ".$display."' onclick='toggleCategory(this);'>&nbsp;</span>";
```

replace with

```
            $html .= "<span id='".$cat['category_id']."_toggler' data-target='#cat".$cat['category_id']."' data-toggle='collapse' class='CategoryToggler ".$display."' aria-expanded='false' aria-controls='cat".$cat['category_id']."'>&nbsp;</span>";

```

same file:
around line 331

```
                $html .= "<ul id='".$catID."_categories' class='sub_categories' style='display:".($display)."'>";
```

replace with:

```
                $html .= "<ul id='cat".$catID."' class='collapse'>";

```

**Comment by sakydev** [comment]
Issue has been resolved. Thank you @mj1985
