### ISSUE TITLE
Photo Upload Issue in File Name extension

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#151]
When you upload photo extension is included Tittle and URL 
e.g
i have a photo with name (Shahid Afridi pic 2015.jpg ) when i upload the photo the pic title is same like
 Shahid Afridi pic 2015.jpg extension is not removing 

here is the exmple in demo site also http://demo.clipbucket.com/view_item.php?item=X7S5M4M5HB1N&type=photos&collection=24

check the .jpeg extension in title and url

thanks

**Comment by sakydev** [comment]
Fixed and committed
