### ISSUE TITLE
Meta Description Issue

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#153]
there is a issue in meta keywords and meta description its showing Default one on every page just title is changing... its big issue for SEO. when you submit your sitemap to google its saying Duplicate description.

<meta name="keywords" content=" Keyword1, keyword2" />
<meta name="description" content="Description goes here" />
<meta name="distribution" content="global" />
<title>Video Title - Site Name</title>

Please set meta description and keywords for videos, photos, channels groups etc..

thanks

**Comment by sakydev** [comment]
Fixed and committed
