### ISSUE TITLE
CB 2.7.6 Template Issue in mobile tablet devices

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#154]
i have notice there is little issue with template in mobile and tablet devices please watch the video.

http://tune.pk/video/6194106/cb-276-template-issue-in-mobile-tablet-devices

there is left right scrolling ...
thanks

**Comment by sakydev** [comment]
Video is asking for a password. @Arman143 Skype me that or just explain the problem

**Comment by Arman143** [comment]
now watch the video i have remove restriction.

**Comment by Arman143** [comment]
now watch the video i have remove restriction.

**Comment by sakydev** [comment]
Will be resolved in ClipBucket's new default theme (yeah, we are working on it) in ClipBucket 2.8.1
