### ISSUE TITLE
Responsivness Issues

### ISSUE THREAD

**Issue by jamilrehman** [arslancb/clipbucketv2#16]
# Header

http://prntscr.com/79kod3
http://prntscr.com/79kfol
http://prntscr.com/79kf9q

on mobile device it will be hide search drop down options
http://prntscr.com/79kmfi

**Comment by jamilrehman** [comment]
# Content area

http://prntscr.com/79kuhj
use here margin: 0 0 -60px;

**Comment by jamilrehman** [comment]
# Content area

http://prntscr.com/79lkbt
it appeared on real device 
can we fix it?

**Comment by usman-des** [comment]
exept ds http://prntscr.com/79lkbt

all issues are resolved n commited
