### ISSUE TITLE
cb Server thumb plugin issue with view photo

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#164]
HI,
       when you activate cb server thumb plugin view photo is showing very small like thumb. check the screen shot... the photo original size is 1024px in width... we want the original photo in view photo page..

![screenshot_1](https://cloud.githubusercontent.com/assets/4317570/10874899/abaeece4-814d-11e5-8354-d9d4aebcc47f.png)

suggestion: Create option under admin area for different sizes like:  
Video Normal thumb size = 
Video Sidebar thumb size = 
Feature Video thumb size = 
View photo Size = original or type height and width in px.
etc

**Comment by sakydev** [comment]
This issue has been resolved.
