### ISSUE TITLE
Duplicate Meta Keyword and Discription

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#169]
Hi,
      Please check on watch_video page there is repeated Meta Keyword, Meta Description and Meta distribution... check the screen shot.

![screenshot_2](https://cloud.githubusercontent.com/assets/4317570/10875089/484dbace-8150-11e5-8d46-25da44b7c36c.png)

**Comment by sakydev** [comment]
Thank you @Arman143 . It has been fixed
