### ISSUE TITLE
Issue in guest comments cb 2.8

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#170]
there is little issue in cb 2.8 guest comments. when guest make long comment like paragraph the text overlaying on button reply - delete - spam.. check the attached screen shot

![screenshot_3](https://cloud.githubusercontent.com/assets/4317570/10875133/b1b9cca0-8150-11e5-888b-f3e46056897c.png)

**Comment by sakydev** [comment]
Fixed. no more overlapping :dancer:  http://prnt.sc/acmzp3

**Comment by Arman143** [comment]
Thank YOu... waiting for 2.8.1
