### ISSUE TITLE
Issue with disabling Photo 

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucketv2#177]
When you disable photos, they can still be uploaded and they stay in big menu as well.

**Comment by mj1985** [comment]
I don't know if it's correct, but I edited my templates with this part:

```
{if $row.photosSection=='yes' }
... code ...
{/if}
```

and it's working for me.

**Comment by sakydev** [comment]
Let's go hunting

**Comment by sakydev** [comment]
Hunted!
