### ISSUE TITLE
Default category for mass_upload not working

### ISSUE THREAD

**Issue by ghost** [arslancb/clipbucketv2#179]
The checkbox 'default category' isn't checked when you try to mass_upload video files. (It works for normal uploads) This makes the mass_upload functionality useless when uploading hundreds of files, because you'll have to tick the box manually for each video. I remember this bug being there from version 2.6 and it is still here in version 2.8. Maybe someone can solve this?
I think I posted a solution years ago on the old forum, but I cannot access it anymore. Now I don't have time to dive into the code again.

Kind regards,

Ruckola

**Comment by mj1985** [comment]
It's not a bug, it's a feature!

I really like that "feature", because I have some videos in the folder that I don't want to upload the same time and of course you have to fill out the description and title.

**Comment by ghost** [comment]
Hello mj1985, first of all thank you for reaction.

I'm glad it works for you, but shouldn't it be more logical to put it the other way around? If you want to exclude files from the 'mass upload' you should be able to uncheck them. Otherwise I don't see the added value over the normal upload procedure. 
If you don't agree, then maybe you can give some advice on how to adjust my workflow then? What I'm trying to accomplish, is to put a lot of video files into the website, get them processed, and then afterwards, add the metadata directly into the database by a script that's matching the titles. The metadata is stored in a large csv file.
I'm pretty sure that I'm not the only one who faces this challenge. By the way, I finally found the old forum which is still available and the 'solution' still works! Here is the link: 
http://forums.clip-bucket.com/showthread.php?8208-Default-Category-on-Mass-Upload-Folder

**Comment by sakydev** [comment]
@ruckola  Thank you for reporting this. This issue has been resolved. Keep using ClipBucket :+1:
