### ISSUE TITLE
Search is not working only for videos properly

### ISSUE THREAD

**Issue by awaistariq123** [arslancb/clipbucketv2#18]
![screenshot from 2015-05-26 18 08 05](https://cloud.githubusercontent.com/assets/12610563/7813189/34538072-03d2-11e5-9983-23b5763f0eb5.png)
![screenshot from 2015-05-26 18 08 10](https://cloud.githubusercontent.com/assets/12610563/7813190/34ed26e6-03d2-11e5-9279-63cb05f22ccf.png)

**Comment by fahad-cb** [comment]
closed
