### ISSUE TITLE
bug in myaccount video page

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucketv2#188]
all user video showing in every user my account page and manage video page.. e.g register fresh account and then goto my account page there is all videoa that not u upload.
check the screenshot in my account page there is admin uploaded videos.

![screenshot_2015-12-23-21-37-41](https://cloud.githubusercontent.com/assets/4317570/11980755/ec36e6d8-a9be-11e5-9a8c-5c073024e079.jpeg)

**Comment by sakydev** [comment]
This isn't an issue but a feature instead. This section is for LATEST VIDEOS which means videos will show up here regardless of who uploaded them.
