### ISSUE TITLE
profile settings and account settings can not be updated

### ISSUE THREAD

**Issue by nisasn** [arslancb/clipbucketv2#189]
1. First of all i see that, under "channel & profile" option, profile settings and account settings have exactly same features ? There is not difference ? Is it designed that way or there is an issue on mine ?
2. When i try to modify the profile and click "update" i get an error "Invalid tags. Kindly review!
   Invalid URL provided."
   Any idea why this is happening ?

Thanx

**Comment by sakydev** [comment]
Fixed and committed.
