### ISSUE TITLE
Visiting a channel/user page

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#19]
At the top it says "unfriend". It gives me an impression that I'm logged in and have added the user as a friend.

How it should be:
The default text (if logged out) should be "befriend" or something.

**Comment by sakydev** [comment]
Issues seems invalid. If a user is not logged in, it shows "add friend" to logged out users. Kindly explain a little more if there is any problem at all.

**Comment by SufianBabri** [comment]
As you can see in the screenshot, I'm not logged in and I see "unfriend":

![screen shot 2015-05-27 at 11 07 36 am](https://cloud.githubusercontent.com/assets/9989266/7829942/d965f232-0460-11e5-9e1f-040380cf6481.png)

**Comment by sakydev** [comment]
Fixed.
