### ISSUE TITLE
channel displays "unfriend" forever, Cannot add again.

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucketv2#191]
After a user unfriends another user, their channel displays "unfriend" forever. It should go back to " Add as friend"

**Comment by nisasn** [comment]
fyi: I found the temporary fix, go to styles/cb_27/layout/blocks/view_channel/channel_header.html
line 11-24 : Follow the instructions in the attachment. Hope it helps.

  
[channelHeader.txt](https://github.com/arslancb/clipbucketv2/files/98955/channelHeader.txt)

**Comment by sakydev** [comment]
Killed
