### ISSUE TITLE
PM does not work when SEO URL is turned on

### ISSUE THREAD

**Issue by nisasn** [arslancb/clipbucketv2#192]
On CB version 2.8, When SEO URL option is turned on, users can not send private massages - an error is thrown "User does not exists" . However, when its turned off they can send PM.

Steps to reproduce the issue

Turn on SEO URL from admin area, and go to "view channel" --- > click one of the users and click "send message", you get an error "user does not exits" Also, it redirects to - http:// your domain /user/private_message.php?mode=new_msg&to={username}
When SEO is turned of, PM works fine. Redirects to - http://your domain/private_message.php?mode=new_msg&to={username}
SO i think there should be a new rule created in .htaccess file for private_message.php ?

**Comment by sakydev** [comment]
Killed.
