### ISSUE TITLE
admin area - member advanced search does not work

### ISSUE THREAD

**Issue by nisasn** [arslancb/clipbucketv2#194]
In admin area ---> Users---> manage members---> advanced search, when I try to search for any username or email it returns "no user found" although the same user is created already. 

Steps to reproduce.
1. In admin area, created a user with username "AAA" 
2. Go to Users---> manage members---> advanced search. In the Username field type "AAA" and click search.
3. Notice it says "No user found" .

**Comment by sakydev** [comment]
Issue is invalid. Both search by username and search by email are working fine.

I will search this user http://prnt.sc/acmtbg

Entered his email http://prnt.sc/acmths

Got the result http://prnt.sc/acmtkv
