### ISSUE TITLE
Collection select on photo upload

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucketv2#207]
Collection select option on photo upload does changes to default collection when uploading 
![1](https://cloud.githubusercontent.com/assets/15014349/13252345/0494f822-da58-11e5-9e3f-6871b0e0873a.PNG)
![2](https://cloud.githubusercontent.com/assets/15014349/13252353/0a31410a-da58-11e5-89bc-3f12f62129af.PNG)

**Comment by sakydev** [comment]
Issue has been resolved.
