### ISSUE TITLE
drop down menu Css not loading properly on searching groups 

### ISSUE THREAD

**Issue by burhaniu** [arslancb/clipbucketv2#21]
![css not loading properly](https://cloud.githubusercontent.com/assets/12610639/7813277/f77a2e8e-03d2-11e5-9f06-a22eef0eea32.png)

**Comment by sakydev** [comment]
![broken group css fixed](https://cloud.githubusercontent.com/assets/10042555/7827588/9def5acc-0442-11e5-880c-252cd23421d0.png)

Issue has been fixed.
