### ISSUE TITLE
Comment from guest user does not display name

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucketv2#216]
User is asked to input name but its not displayed.
![comment](https://cloud.githubusercontent.com/assets/15014349/13428815/9d1e96bc-dfde-11e5-89e3-78233ae0b37b.PNG)
![guest comment](https://cloud.githubusercontent.com/assets/15014349/13428816/9d555dc8-dfde-11e5-9ed0-90a1252997ba.PNG)

**Comment by sakydev** [comment]
Killed.
