### ISSUE TITLE
Issue with script's Server module checker

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucketv2#218]
script checks /usr/bin/ffmpeg but ffmpeg (when following there own install guide) installs to /usr/local/bin/ffmpeg 
 (also it's misspelled as missing ectention instead of extension)

**Comment by sakydev** [comment]
Issue doesn't make sense. FFMPEG is checked in path that user inputs from Website Settings & Configurations settings. There is no static checking for it. Closing now.
