### ISSUE TITLE
User/channel details

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#22]
On <code>~/f-clipbucket27/channels.php</code>, admin has photos count in negative.

Screenshot of the said issue:

![screen shot 2015-05-26 at 6 13 50 pm](https://cloud.githubusercontent.com/assets/9989266/7813281/066be612-03d3-11e5-8af0-d54e9098acd6.png)

**Comment by sakydev** [comment]
Issue resolved.
