### ISSUE TITLE
Upgraded to v2.8 and now all links are not working

### ISSUE THREAD

**Issue by 915855** [arslancb/clipbucketv2#226]
I upgraded to v2.8 from an older version successfully but all my links are missing the .php extension and I get page not found when I click on any of them. If I add the .php extension to the all the links, they will open successfully. Can someone please help me solve this problem. How can I add the .php extension to all my links so that they work properly.

If you click on any link, you will get page not found. Since the .php extension is not working on all the links, the clipbucket error page is not showing, instead my main domain error page will show since I uploaded clipbucket to a subdirectory of my main domain name. If you just add .php to the end of the links, they all will work. Please help!

Thank you.

**Comment by 915855** [comment]
I was able to get some of the links to work by adding the following code below to the htaccess file but not all of them are working. I Opened/Edited the file .htaccess in my root-folder and added this . 

After
RewriteEngine on
added
RewriteBase /my_folder/

Now some of the links work but not all of them. Can someone please help me fix this problem. Thank you.

**Comment by 915855** [comment]
This is such a popular script but nobody helps you with anything.

**Comment by arslancb** [comment]
Hi
i am sorry about that, the thing is you your SEO URLs are on, you can turn
them off by going to the settings Panel, look for SEO URLs

you also have .htaccess file included in the source this should have fixed
your problem
