### ISSUE TITLE
play pause icon issue on video player

### ISSUE THREAD

**Issue by usman-des** [arslancb/clipbucketv2#23]
on watch video page while video loading n loader image appearing, at bottom bar play icon seems to be ok bt when play icon appear , play icon @ bottom bar convert into pause icon .....jo kay boht galt baat ha
![iw11-pause](https://cloud.githubusercontent.com/assets/12610585/7813287/0be4ea80-03d3-11e5-96fd-cf2130ea3528.jpg)
![chrome-paly-pause-issue](https://cloud.githubusercontent.com/assets/12610585/7813291/17a9ca98-03d3-11e5-831b-8bcaedca4e46.jpg)

**Comment by fahad-cb** [comment]
fixed
