### ISSUE TITLE
Search bar UI

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#25]
It should be more like Google's search bar where the go/search button is at the right and the dropdown/arrow-button is at its left.

Also, the search parameter (video, channel, etc) should be shown in the search bar to make it easy for user to re-orientate when returning from the other page.

![screen shot 2015-05-26 at 6 55 49 pm](https://cloud.githubusercontent.com/assets/9989266/7814037/e9593f88-03d8-11e5-8324-b78a89520047.png)

**Comment by SufianBabri** [comment]
In clarification of my second point, the following picture shows a dropdown at the left of the "Go" button. This dropdown shows the currently selected item, making the user quickly understand what he is searching and/or that there's an option where he could choose to search Videos, Channels, etc:

![searchbar ui](https://cloud.githubusercontent.com/assets/9989266/7829538/c465453a-045c-11e5-8525-002dc28f6336.png)

<b>Note:</b> the dropdown isn't necessarily needed to be inside the searchbar, but showing its selected item is.

**Comment by fahad-cb** [comment]
fixed
