### ISSUE TITLE
Search results UI

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#26]
Current page shouldn't be clickable.
Why? Because that's how we normally see.

Also, there's the incomplete sentence. Please fix it too.
![screen shot 2015-05-26 at 6 34 24 pm](https://cloud.githubusercontent.com/assets/9989266/7813717/a57934be-03d6-11e5-8f1a-4df4881bad7b.png)

**Comment by sakydev** [comment]
Incomplete sentence problem has been fixed. Link is not actually clickable and takes you no where. That is how it is in all of ClipBucket pages.

**Comment by SufianBabri** [comment]
"Searching 's' in" is fixed for Videos, Groups and Photos but when searching "Channels" it still is incomplete.

![screen shot 2015-05-27 at 11 23 49 am](https://cloud.githubusercontent.com/assets/9989266/7830131/de3e2bb0-0462-11e5-9267-6891035a8197.png)

**Comment by sakydev** [comment]
It has not been updated on live version yet. But is fixed. That is the case with all issues that are being fixed. They all will be updated in once on live site.
