### ISSUE TITLE
Tab loading on Channel/user's page is confusing (UX issue)

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#27]
The "Playlists" tab is loading but the tab is showing the content of previously selected "info" tab.

![screen shot 2015-05-26 at 6 44 08 pm](https://cloud.githubusercontent.com/assets/9989266/7813819/72a99bcc-03d7-11e5-8ca3-c137a74b11c1.png)

**Comment by sakydev** [comment]
Content is supposed to be hidden once the content of next tab shows. Invalid issue.

**Comment by SufianBabri** [comment]
Let me explain the problem again.
When you switch tab (first time switching to any tab not previously loaded), the content of the previous tab (like in the screenshot above, the "info" tab's data) will be kept showing till the new selected tab's (playlist in screenshot) data is not loaded.

**Steps to reproduce:**
1. Open http://107.181.179.12/f-clipbucket27/view_channel.php?user=admin
2. click on the tab "Groups",
3. you can see the spinner/progress indicator spin against the tab title but the tab's content is still showing the old data (i.e of the "Info" tab). This is a UX problem.

**Expected behaviour:**
The old tab's content should be replaced by a progress indicator to indicate the user "data is being loaded".
