### ISSUE TITLE
Some channels don't show up only in search

### ISSUE THREAD

**Issue by SufianBabri** [arslancb/clipbucketv2#31]
They are probably the ones which aren't activated, however, is this a desired behaviour?

All channels:
![screen shot 2015-05-26 at 7 03 35 pm](https://cloud.githubusercontent.com/assets/9989266/7814207/19b71d70-03da-11e5-8155-3c5fc1bc04f2.png)

Channels in search results:
![screen shot 2015-05-26 at 6 55 49 pm](https://cloud.githubusercontent.com/assets/9989266/7814244/51346f3c-03da-11e5-82b6-b0170244a8ba.png)

**Comment by sakydev** [comment]
Issue has been resolved.
