### ISSUE TITLE
On cover section the Videos,contacts,photos,views tabs are not showing properly 

### ISSUE THREAD

**Issue by awaistariq123** [arslancb/clipbucketv2#42]
![screenshot from 2015-06-01 16 07 54](https://cloud.githubusercontent.com/assets/12610563/7911567/aaa7eb0a-0878-11e5-833c-a1cce916f6cb.png)

**Comment by usman-des** [comment]
done

**Comment by usman-des** [comment]
n i also done cover to responsive till 320px n removed unnecessary code ,write simple n clean code n indexed too
