### ISSUE TITLE
Password prodected Video

### ISSUE THREAD

**Issue by fahad-cb** [arslancb/clipbucketv2#49]
If  a video is password protected , no option to view this video 

![videos](https://cloud.githubusercontent.com/assets/12268115/7912203/d64fe4aa-087e-11e5-9c5e-37cb2a4e2990.png)

**Comment by fahad-cb** [comment]
fixed

**Comment by epicPenguin** [comment]
If we give  a password to any video , it does not ask  for password. it directly plays the video.
