### ISSUE TITLE
The player size is not stable. Sometimes it gets so humongous and sometimes so small.(in next versions)

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#57]
Play a video and toggle the player size more than once. 
![check_out_the_size_of_the_player](https://cloud.githubusercontent.com/assets/12610575/7913100/4c2043da-0886-11e5-83d1-6df46bc1d9a7.png)
![this_is_how_smal_the_player_gets](https://cloud.githubusercontent.com/assets/12610575/7913104/5893e4a0-0886-11e5-82e0-8e57107ddffe.png)

**Comment by sakydev** [comment]
Issue has been resolved.
