### ISSUE TITLE
Player: Once muted if we refresh the page it again becomes unmuted.(in next versions)

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#60]
Steps:

1- Play a video.
2- Mute the volume.
3- Refresh the page.

Actual Result: 
It is unmuted.

Expected Result:
It should come as mute.
![once_muted_when_came_next_time_it_is_unmute](https://cloud.githubusercontent.com/assets/12610575/7913288/2379eb64-0888-11e5-8182-aab3b73efefc.png)

**Comment by sakydev** [comment]
Issue has been resolved.
