### ISSUE TITLE
photo sec (for Next Version)

### ISSUE THREAD

**Issue by usman-des** [arslancb/clipbucketv2#62]
for example...
1st person comment under the photo
2nd n 3rd person reply to 1st person bt 1st's comment is repeating.....

**Comment by usman-des** [comment]
![cloudy with a chance of meatballs 2 revenge leftovers wallpaper jpg usman des - clipbucket v2 7 beta 2015-06-01 18-05-18](https://cloud.githubusercontent.com/assets/12610585/7913512/fec522aa-0889-11e5-9108-99d70a6ad2f3.png)

**Comment by fahad-cb** [comment]
this feature will be enhanced Later

**Comment by sakydev** [comment]
Issue was resolved by @fahad-cb  a little time ago. Currently working fine in ClipBucket.

http://prntscr.com/acynwg
