### ISSUE TITLE
Player: The fullscreen button doesn't change when gone in the fullscreen.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#64]
Steps:

1- Play  a video.
2- Click the full screen button.
3- See the full screen button once it is gone into the fullscreen.

Actual Result:
It is not changed.

Expected Result:
The button should be changed.

![this_button_doesn t_changes](https://cloud.githubusercontent.com/assets/12610575/7913624/de8cb632-088a-11e5-915e-f7ea919d6c68.png)

**Comment by epicPenguin** [comment]
This issue is not fixed. The message and the button is not changed.

**Comment by sakydev** [comment]
Issue has been fixed for CB_video_js
