### ISSUE TITLE
The message shown is not upto the mark when invalid video link is given.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#79]
Steps:
1- Go to upload video page.
2- Click the Remote Upload tab.
3- Give the invalid link.

![awkward_way_to_show_message](https://cloud.githubusercontent.com/assets/12610575/7933466/c43503da-0938-11e5-8fc6-422c80837e69.png)

**Comment by sakydev** [comment]
Issue killed!
