### ISSUE TITLE
Photo Upload: After uploading when we click on 'Save Details' it actually does nothing.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#83]
Note: The message is shown but it is not visible too.
![clicking_on_save_details_doesn t_do_anything](https://cloud.githubusercontent.com/assets/12610575/7933615/c819fbbc-0939-11e5-9359-ca9419470b4e.png)

**Comment by sakydev** [comment]
It displays message but that is at top so you couldn't see it.
