### ISSUE TITLE
Sign up date of birth css is not loading 

### ISSUE THREAD

**Issue by awaistariq123** [arslancb/clipbucketv2#9]
![screenshot from 2015-05-26 17 44 30 - 2](https://cloud.githubusercontent.com/assets/12610563/7812870/7ba8cf34-03cf-11e5-89e8-4e7257178a39.png)

**Comment by saqirzzq** [comment]
Fixed and committed. 
![Uploading dob css fixed.png…]()

**Comment by sakydev** [comment]
![dob css fixed](https://cloud.githubusercontent.com/assets/10042555/7827469/09f1f24a-0441-11e5-9535-7a032665f7ea.png)
Fixed and committed.
