### ISSUE TITLE
Watch Video: Like and dislike is clicked only once, either u can like or dislike.

### ISSUE THREAD

**Issue by epicPenguin** [arslancb/clipbucketv2#91]
Steps:
1- Play a video.
2- Like it.
3- Try to dislike it.

You wouldn't be able to like or dislike.
![like_or_dislike_only_once](https://cloud.githubusercontent.com/assets/12610575/7933929/6e400566-093c-11e5-9cfc-75912e58ea39.png)

**Comment by fahad-cb** [comment]
saved for Future
